/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Validacoes.Validar;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Anamnese;
import model.dao.AnamneseDAO;
import static view.AlterarAnamnesePaciente.codconsulta;

/**
 *
 * @author User
 */
public class CadastrarAnamnesePaciente extends javax.swing.JFrame {

    public static int codconsulta;
    private static int codanamnese;

    /**
     * Creates new form ManterAnamnese
     */
    public CadastrarAnamnesePaciente(int cod) {
        initComponents();
        codconsulta = cod;
        Anamnese a2 = new Anamnese();
        AnamneseDAO dao2 = new AnamneseDAO();
        a2 = dao2.ReadAnamneseConsulta(codconsulta);
        codanamnese = a2.getCodAnamnese();
        boolean existe = readcampos();
        if (existe) {
            jLabel8.setText("Lendo dados da Anamnese Cadastrada na consulta");
        } else {
            jLabel8.setText(" Cadastrar anamnese na consulta");
        }
        System.out.println(codconsulta);
        System.out.println(codanamnese);
    }

    public boolean readcampos() {
        Anamnese a = new Anamnese();
        AnamneseDAO dao = new AnamneseDAO();
        a = dao.ReadAnamneseConsulta(codconsulta);
        codanamnese = a.getCodAnamnese();
        if (codanamnese != 0) {

            TxtQueixaPrincipal.setText(a.getQueixaPrincipal());
            InicioDaQueixa.setText((String) Validar.fDataNascBD((Date) a.getInicioDaQueixa()));
            JCBSubita.setSelectedItem(a.getSubitaOuProgressiva());
            TxtQueixasSecundarias.setText(a.getQueixasSecundarias());
            TxtHistoricoFamiliar.setText(a.getHistoricoFamiliar());
            TxtDiagnostico.setText(a.getDiagnostico());
            TxtEncaminhamento.setText(a.getEncaminhamento());
            TxtDoencasConhecidas.setText(a.getDoencasConhecidas());
            TxtMedicamentosUtilizados.setText(a.getMedicamentosUtilizados());
            TxtOqueMudou.setText(a.getOqueMudou());
            TxtSintomas.setText(a.getSintomas());
            TxtComoComecou.setText(a.getComoComecou());
            JCBQueixasCognitivas.setSelectedItem(a.getQueixasCognitivas());
            JCBQueixasAfetivoEmocionais.setSelectedItem(a.getQueixasAfetivoEmocionais());
            JCBPsicomotricidade.setSelectedItem(a.getPsicomotricidade());
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnVoltar = new javax.swing.JButton();
        queixa = new javax.swing.JLabel();
        sp = new javax.swing.JLabel();
        TxtQueixaPrincipal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtQueixasSecundarias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtHistoricoFamiliar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDiagnostico = new javax.swing.JTextField();
        encaminhamento = new javax.swing.JLabel();
        TxtEncaminhamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtDoencasConhecidas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtMedicamentosUtilizados = new javax.swing.JTextField();
        BtnCadastrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtOqueMudou = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtSintomas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtComoComecou = new javax.swing.JTextField();
        JCBQueixasCognitivas = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JCBQueixasAfetivoEmocionais = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        JCBPsicomotricidade = new javax.swing.JComboBox<>();
        JCBSubita = new javax.swing.JComboBox<>();
        brnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        InicioDaQueixa = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manter Anamnese");
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        queixa.setText("QueixaPrincipal");

        sp.setText("SubitaOUProgressiva");

        jLabel2.setText("InicioDaQueixa");

        jLabel3.setText("QueixasSecundarias");

        jLabel4.setText("HistoricoFamiliar");

        jLabel5.setText("Diagnostico");

        encaminhamento.setText("Encaminhamento");

        jLabel6.setText("Doencas Conhecidas");

        jLabel7.setText("Medicamentos Utilizados");

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        jLabel9.setText("OqueMudou");

        jLabel10.setText("Sintomas");

        jLabel11.setText("ComoComecou");

        JCBQueixasCognitivas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Nenhuma", "Integridade Sensorial","Percepção", "Atenção", "Memória" }));

        jLabel12.setText("QueixasCognitivas");

        jLabel13.setText("QueixasAfetivoEmocionais");

        JCBQueixasAfetivoEmocionais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Nenhuma", "Volição", "Afeto", "Ansiedade", "Medo", "Culpa", "Raiva", "Luto", "Desanimo" }));

        jLabel14.setText("Psicomotricidade");

        JCBPsicomotricidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Lento", "Agitado"}));

        JCBSubita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subita","Progressiva" }));

        brnAlterar.setText("Alterar");
        brnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setText("jLabel8");
        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(encaminhamento)
                            .addComponent(jLabel4)
                            .addComponent(sp)
                            .addComponent(queixa)
                            .addComponent(BtnVoltar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtComoComecou)
                                    .addComponent(TxtOqueMudou)
                                    .addComponent(TxtMedicamentosUtilizados, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(TxtEncaminhamento)
                                    .addComponent(TxtHistoricoFamiliar)
                                    .addComponent(TxtQueixaPrincipal)
                                    .addComponent(JCBQueixasAfetivoEmocionais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JCBSubita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtQueixasSecundarias)
                                        .addComponent(TxtDiagnostico)
                                        .addComponent(TxtDoencasConhecidas, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(JCBQueixasCognitivas, 0, 183, Short.MAX_VALUE)
                                        .addComponent(TxtSintomas))
                                    .addComponent(JCBPsicomotricidade, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InicioDaQueixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queixa)
                    .addComponent(TxtQueixaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(InicioDaQueixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp)
                    .addComponent(jLabel3)
                    .addComponent(TxtQueixasSecundarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBSubita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtHistoricoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encaminhamento)
                    .addComponent(TxtEncaminhamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtDoencasConhecidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtMedicamentosUtilizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtOqueMudou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBQueixasCognitivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtComoComecou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JCBPsicomotricidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBQueixasAfetivoEmocionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar)
                    .addComponent(brnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        // TODO add your handling code here:
        Anamnese a = new Anamnese();
        AnamneseDAO dao = new AnamneseDAO();
if(!Validar.vCamposVaziosAnm(this, TxtQueixaPrincipal, InicioDaQueixa) ) {
        if (codanamnese == 0) {

            a.setQueixaPrincipal(TxtQueixaPrincipal.getText());
            a.setSubitaOuProgressiva((String) JCBSubita.getSelectedItem());

            //java.util.Date date = new java.util.Date();
            Object param = InicioDaQueixa.getDate();
            a.setInicioDaQueixa(param);
            a.setQueixasSecundarias(TxtQueixasSecundarias.getText());
            a.setHistoricoFamiliar(TxtHistoricoFamiliar.getText());
            a.setDiagnostico(TxtDiagnostico.getText());
            a.setEncaminhamento(TxtEncaminhamento.getText());
            a.setDoencasConhecidas(TxtDoencasConhecidas.getText());
            a.setMedicamentosUtilizados(TxtMedicamentosUtilizados.getText());
            a.getConsulta().setCodConsulta(codconsulta);
            a.setOqueMudou(TxtOqueMudou.getText());
            a.setSintomas(TxtSintomas.getText());
            a.setComoComecou(TxtComoComecou.getText());
            a.setQueixasCognitivas((String) JCBQueixasCognitivas.getSelectedItem());
            a.setQueixasAfetivoEmocionais((String) JCBQueixasAfetivoEmocionais.getSelectedItem());
            a.setPsicomotricidade((String) JCBPsicomotricidade.getSelectedItem());
            boolean sucesso = dao.Create(a);
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Anamnese Inserida Com Sucesso");
                a = dao.ReadAnamneseConsulta(codconsulta);
                codanamnese = a.getCodAnamnese();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não é possivel cadastrar mais de uma anamnese por consulta");
        }

}
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        // TODO add your handling code here:
            AlterarConsultapelomenu.codconsulta = codconsulta;
            AlterarConsultapelomenu cp = new AlterarConsultapelomenu();
            cp.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void brnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnAlterarActionPerformed
        // TODO add your handling code here:
        Anamnese a = new Anamnese();
        AnamneseDAO dao = new AnamneseDAO();
        Anamnese a2 = new Anamnese();
        AnamneseDAO dao2 = new AnamneseDAO();
        a2 = dao2.ReadAnamneseConsulta(codconsulta);
        a.setCodAnamnese(a2.getCodAnamnese());
        if (a.getCodAnamnese() != 0) {
            a.setQueixaPrincipal(TxtQueixaPrincipal.getText());
            a.setSubitaOuProgressiva((String) JCBSubita.getSelectedItem());

            //java.util.Date date = new java.util.Date();
            Object param = InicioDaQueixa.getDate();
            a.setInicioDaQueixa(param);
            a.setQueixasSecundarias(TxtQueixasSecundarias.getText());
            a.setHistoricoFamiliar(TxtHistoricoFamiliar.getText());
            a.setDiagnostico(TxtDiagnostico.getText());
            a.setEncaminhamento(TxtEncaminhamento.getText());
            a.setDoencasConhecidas(TxtDoencasConhecidas.getText());
            a.setMedicamentosUtilizados(TxtMedicamentosUtilizados.getText());
            a.getConsulta().setCodConsulta(codconsulta);
            a.setOqueMudou(TxtOqueMudou.getText());
            a.setSintomas(TxtSintomas.getText());
            a.setComoComecou(TxtComoComecou.getText());
            a.setQueixasCognitivas((String) JCBQueixasCognitivas.getSelectedItem());
            a.setQueixasAfetivoEmocionais((String) JCBQueixasAfetivoEmocionais.getSelectedItem());
            a.setPsicomotricidade((String) JCBPsicomotricidade.getSelectedItem());

            boolean sucesso = dao.Update(a);
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Anamnese Alterada Com Sucesso");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não existe Anamnese cadastrada nesta consulta");

        }
    }//GEN-LAST:event_brnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (codanamnese != 0) {
            boolean sucesso = false;
            Anamnese a = new Anamnese();
            AnamneseDAO dao = new AnamneseDAO();
            a.setCodAnamnese(codanamnese);
            sucesso = dao.Delete(a);
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Anamnese Excluida Com Sucesso");
                codanamnese = 0;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não Existe uma anamnese cadastrada nesta consulta");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAnamnesePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAnamnesePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAnamnesePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAnamnesePaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAnamnesePaciente(codconsulta).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnVoltar;
    private com.github.lgooddatepicker.components.DatePicker InicioDaQueixa;
    private javax.swing.JComboBox<String> JCBPsicomotricidade;
    private javax.swing.JComboBox<String> JCBQueixasAfetivoEmocionais;
    private javax.swing.JComboBox<String> JCBQueixasCognitivas;
    private javax.swing.JComboBox<String> JCBSubita;
    private javax.swing.JTextField TxtComoComecou;
    private javax.swing.JTextField TxtDiagnostico;
    private javax.swing.JTextField TxtDoencasConhecidas;
    private javax.swing.JTextField TxtEncaminhamento;
    private javax.swing.JTextField TxtHistoricoFamiliar;
    private javax.swing.JTextField TxtMedicamentosUtilizados;
    private javax.swing.JTextField TxtOqueMudou;
    private javax.swing.JTextField TxtQueixaPrincipal;
    private javax.swing.JTextField TxtQueixasSecundarias;
    private javax.swing.JTextField TxtSintomas;
    private javax.swing.JButton brnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel encaminhamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel queixa;
    private javax.swing.JLabel sp;
    // End of variables declaration//GEN-END:variables
}
