/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Anamnese;
import model.bean.Anotacao;
import model.bean.Consulta;
import model.bean.Paciente;
import model.dao.AnamneseDAO;
import model.dao.AnotacaoDAO;
import model.dao.ConsultaDAO;
import model.dao.PacienteDAO;
import static view.ExibirAnotacoesPaciente.codpaciente;

/**
 *
 * @author User
 */
public class ExibirAnamnesesPaciente extends javax.swing.JFrame {
    public static int codpaciente;
    /**
     * Creates new form ExibirAnamneses
     */
    public ExibirAnamnesesPaciente() {
        initComponents();
         PacienteDAO pdao = new PacienteDAO();
         Paciente p = new Paciente();
         p = pdao.ReadPaciente(codpaciente);
         lNome.setText(p.getNome_Completo());
         DefaultTableModel dtmPacientes = (DefaultTableModel) JTAnamneses.getModel();
        JTAnamneses.setRowSorter(new TableRowSorter(dtmPacientes));
        ReadJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnVoltar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAnamneses = new javax.swing.JTable();
        lNome = new javax.swing.JLabel();
        BtnExcluirAnamnese = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Exibindo anamnese do paciente");

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        JTAnamneses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodAnamnese", "QueixaPrincipal", "SubitaOuProgressiva", "InicioDaQueixa", "QueixasSecundárias", "HistoricoFamiliar", "Diagnostico", "Encaminhamento", "DoencasConhecidas", "MedicamentosUtilizados", "OQueMudou", "Sintomas", "ComoComecou", "QueixasCognitivas", "QueixasAfetivoEmocionais", "Psicomotricidade", "CodConsulta", "DataEmissão"
            }
        ));
        jScrollPane1.setViewportView(JTAnamneses);

        lNome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lNome.setText("jLabel2");

        BtnExcluirAnamnese.setText("Excluir");
        BtnExcluirAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirAnamneseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExcluirAnamnese)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnVoltar)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNome)
                        .addGap(137, 137, 137))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtnVoltar)
                    .addComponent(lNome))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluirAnamnese))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:
        if (JTAnamneses.getSelectedRow() != -1) {

            AlterarAnamnesePaciente.codconsulta = ((int) JTAnamneses.getValueAt(JTAnamneses.getSelectedRow(), 16));
            AlterarAnamnesePaciente cp = new AlterarAnamnesePaciente();
            cp.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta para alterar");
        }
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
ManterPaciente mp1 = new ManterPaciente();
        mp1.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnExcluirAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirAnamneseActionPerformed
        // TODO add your handling code here:
        if (JTAnamneses.getSelectedRow() != -1) {

            Anamnese a = new Anamnese();
            AnamneseDAO adao = new AnamneseDAO();
            a.setCodAnamnese((int) JTAnamneses.getValueAt(JTAnamneses.getSelectedRow(), 0));
              boolean sucesso = adao.Delete(a);
              
              if(sucesso){
                              JOptionPane.showMessageDialog(this, "Anamnese Apagada com Sucesso");
                              

              }
          
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma anamnese para excluir");
        }
        ReadJTable();
    }//GEN-LAST:event_BtnExcluirAnamneseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirAnamnesesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirAnamnesesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirAnamnesesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirAnamnesesPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirAnamnesesPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnExcluirAnamnese;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JTable JTAnamneses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNome;
    // End of variables declaration//GEN-END:variables

    private void ReadJTable() {
          DefaultTableModel model = (DefaultTableModel) JTAnamneses.getModel();
        model.setNumRows(0);
        AnamneseDAO dao = new AnamneseDAO();
        ConsultaDAO cdao = new ConsultaDAO();
        
        
        for (Consulta c : cdao.Read(codpaciente)) {
            List<Anamnese> a = new ArrayList<>();
             a = (List<Anamnese>) dao.Read(c);
             
            for (int i = 0; i < a.size(); i++){
            model.addRow(new Object[]{
                a.get(i).getCodAnamnese(),    
                a.get(i).getQueixaPrincipal(),
                a.get(i).getSubitaOuProgressiva(),
                a.get(i).getInicioDaQueixa(),
                a.get(i).getQueixasSecundarias(),
                a.get(i).getHistoricoFamiliar(),
                a.get(i).getDiagnostico(),
                a.get(i).getEncaminhamento(),
                a.get(i).getDoencasConhecidas(),
                a.get(i).getMedicamentosUtilizados(),
                
                a.get(i).getOqueMudou(),
                a.get(i).getSintomas(),
                a.get(i).getComoComecou(),
                a.get(i).getQueixasCognitivas(),
                a.get(i).getQueixasAfetivoEmocionais(),
                a.get(i).getPsicomotricidade(),
                a.get(i).getConsulta().getCodConsulta(),
               a.get(i).getDataEmissao(),

            });
        }
    }
    }
}
